services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: rustle:dev
    container_name: rustle-dev
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: cargo run

  db:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "SYqujNZNmvEw2Ajk"
      POSTGRES_DB: "rustle"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rustle"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
