services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: rustle-backend:latest
    container_name: rustle-backend
    restart: always
    environment:
      ROCKET_PROFILE: production
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      ROCKET_SECRET_KEY: ${RUSTLE_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15
    container_name: rustle-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: rustle-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
